version: 2.1
orbs:
  node: circleci/node@4.5.0
  puppeteer: threetreeslight/puppeteer@0.1.2
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - puppeteer/install
      - run:
          name: Unit test
          command: npm run test:unit
      - run:
          name: E2E test
          command: npm run test:e2e

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test