version: "3"
services:
  api:
    build: ./api
    environment:
      FRONT_DOMAIN: localhost:8081
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: password
    ports:
      - "3316:3306"
  front:
    build: ./front
    environment:
      VUE_APP_API_ENDPOINT: http://localhost:3000
    volumes:
      - ./front:/app
    ports:
      - "8081:8080"
    init: true
    tty: true
    stdin_open: true
    command: npm run serve

volumes:
  bundle: